# For more info on HTTP files go to https://aka.ms/vs/httpfile
POST https://eddbotbackend.azurewebsites.net/api/Category
Content-Type: application/json

{
    "Category":"Category1"
}

###

POST https://eddbotbackend.azurewebsites.net/api/Threads
Content-Type: application/json

{
    "Category":"Category1",
    "Channel":"Team1",
    "Threads":[
        "product", "frontend", "backend"
    ]
}